name: artifact

on: [push]

env: 
  ARTIFACT_NAME: myartifact
  
jobs:
  main:
  run-on: ubuntu-latest
  steps:
    -name: Chekout the code
     uses: actions/checkout@v2
    -name: Upload the artifact
     uses: actions/upoad-artifact@v2
     with: 
      name: ${{ env.ARTIFACT_NAME }}
      path: .
